image: docker:stable
# 0.0.4
# Anchors  
.docker_login: &docker_login
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

.build_container_image:
  script:
    - *docker_login
    - cd $dir
    - docker pull $CI_REGISTRY_IMAGE/$image_name:latest || true
    - du -h -d 1
    - docker build -f ./$dockerfile --cache-from $CI_REGISTRY_IMAGE/$image_name:latest $docker_build_extra_args
      --tag $CI_REGISTRY_IMAGE/$image_name:$CI_COMMIT_SHORT_SHA
      --tag $CI_REGISTRY_IMAGE/$image_name:latest
      --tag $CI_REGISTRY_IMAGE/$image_name:test
      ${docker_build_context:-.}
    - docker push $CI_REGISTRY_IMAGE/$image_name:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/$image_name:latest
    - docker push $CI_REGISTRY_IMAGE/$image_name:test

.promote:
  script:
    - *docker_login
    - docker pull $CI_REGISTRY_IMAGE/$image_name:$existing_tag
    - docker tag $CI_REGISTRY_IMAGE/$image_name:$existing_tag $CI_REGISTRY_IMAGE/$image_name:$new_tag
    - docker push $CI_REGISTRY_IMAGE/$image_name:$new_tag

.security_scan:
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - apk add --no-cache curl docker-cli
    - curl -sSL -o /tmp/trivy-gitlab.tpl https://github.com/aquasecurity/trivy/raw/main/contrib/gitlab.tpl
    - *docker_login
    - trivy image --clear-cache
    - docker pull $CI_REGISTRY_IMAGE/$image_name:$image_tag
    - trivy image --exit-code 0 --no-progress --severity "UNKNOWN,HIGH,CRITICAL" --format template --template "@/tmp/trivy-gitlab.tpl" -o gl-container-scanning-report.json $CI_REGISTRY_IMAGE/$image_name:$image_tag
    - trivy image --exit-code 0 --no-progress --severity "UNKNOWN,HIGH,CRITICAL" -o gl-container-scanning-report.txt $CI_REGISTRY_IMAGE/$image_name:$image_tag
    - trivy image --exit-code 0 --no-progress --severity "UNKNOWN,HIGH,CRITICAL" $CI_REGISTRY_IMAGE/$image_name:$image_tag
    - trivy --quiet image --exit-code $exit_code_when_found --no-progress --severity CRITICAL $CI_REGISTRY_IMAGE/$image_name:$image_tag >/dev/null
  artifacts:
    paths:
      - gl-container-scanning-report.json
      - gl-container-scanning-report.txt




# Stages
stages:
- build
- deploy

build_dependencies:
  stage: build
  variables:
    dir: .
    image_name: clarin-dspace-dependencies
    dockerfile: Dockerfile.dependencies
    docker_build_extra_args: " "
  extends:
   - .build_container_image
  when: manual

build_container:
  stage: build
  variables:
    docker_build_extra_args: "--build-arg DSPACE_DEPENDENCY_IMAGE=itgit.app.uib.no:4567/ub/clarino/clarin-dspace/clarin-dspace-dependencies:latest"
    image_name: clarin-dspace
    dockerfile: Dockerfile
    dir: .
  extends:
    - .build_container_image
  needs: ['build_dependencies']
  when: manual


build_postgres_container:
  stage: build
  variables:
    docker_build_extra_args: "--build-arg POSTGRES_VERSION=13 --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
    image_name: dspace-postgres-pgcrypto-curl
    dockerfile: Dockerfile
    dir:  ./dspace/src/main/docker/dspace-postgres-pgcrypto-curl/
  extends:
    - .build_container_image

build_solr_container:
  stage: build
  variables:
    docker_build_extra_args: ""
    image_name: dspace-solr
    dockerfile: Dockerfile
    dspace_docker_context:  "../../../../solr/"
    dir:  ./dspace/src/main/docker/dspace-solr/
  extends:
    - .build_container_image

promote_prod:
  stage: deploy
  variables:
   existing_tag: $CI_COMMIT_SHORT_SHA
  parallel:
    matrix:
    - image_name: 
      - clarin-dspace
      - clarin-dspace-dependencies
      - dspace-postgres-pgcrypto-curl
      - dspace-solr
  before_script:
    - apk add git
    - new_tag=$(git describe --tags | tr "-" "." | cut -d "." -f1-3 | grep "[0-9]\.[0-9]\.[0-9]" || echo "$(git describe --tags).0")
    - echo "Existing tag is $existing_tag, new tag is $new_tag"
  extends:
    - .promote
  when: manual
